### ISSUE TITLE
Timer features

### ISSUE THREAD

**Issue by santanaguy** [santanaguy/teamodoro#5]
- [x] UI to create a simple timer #6 
- [ ] Persist the timer on the backend #11
- [ ] Allow the user to stop/pause/restart the timer #10 
- [ ] Allow the timer to be shared by link
- [ ] Have the timer syncing between hosts regularly
- [ ] Allow the user to specify multiple timer phases
- [ ] Play a tune when the phase ends
- [ ] Private vs public timers
